Configuração do projeto de acordo com a referência do Esqueleto
martinssegudo/motor-credito-java pull request #1
Opened 2022-02-07 14:05 UTC by yasminwz

Nesse PR realizei as seguintes modificações
1.Remoção do .README
2. Criação de pacotes de acordo com a arquitetura exibida no esqueleto
3. Configurações Swagger
4. Criação das demais entidades, interfaces 
obs. Criei algumas classes de acordo com o Esqueleto, apenas como uma guia para eu poder modificar conforme as 
demandas que serão aplicadas, porém caso necessário, renomearei as classes de acordo com os padrões requisitados

2022-02-07 15:02 UTC, martinssegudo requested changes
Favor nas próximas branchs utilizar a nomenclatura do do gitflow, como no exemplo abaixo:
feature/<nome-branch>
Favor verificar os pontos de atenção.

2022-02-07 15:02 UTC, martinssegundo commented on src/main/java/br/com/motor/config/SwaggerConfig.java
> +
Favor melhorar essa descrição, precisa de ua descrição do que essa aplicação faz, por exemplo:
Api para cálculo de credito disponível para clientes

2022-02-07 15:02 UTC, martinssegundo commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
Favor mudar o nome do banco de dados para refletir o serviço que esta associado a este banco.

2022-02-07 19:17 UTC, martinssegudo commented
Não seguiu TDD e não construiu testes unitários!

2022-02-07 22:29 UTC, yasminwz commented on src/main/java/br/com/motor/config/SwaggerConfig.java
> +
Farei a modificação

2022-02-07 22:29 UTC, yasminwz commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:testdb
Okay!

2022-02-11 01:09 UTC, martinssegudo approved these changes

2022-02-11 01:09 UTC, merged